name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.0.6
  #- numpy=1.26.4      # Fixing numpy missing. 
  - numpy=1.23.5           # Fixing numpy np.object failure, turns out numpy must bye 1.23.5 or higher with mlflow 1.14.1
  - protobuf=3.20.*   # Fixing protobuf import error
  - pip:
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
      - databricks-cli==0.18.0    # fixes the import crash caused by outdated course work files
      - setuptools<81             # silences pkg_resources deprecation
      #- numpy==1.26.4             # <— belt & suspenders so pip won’t upgrade to 2.x
      - numpy==1.23.5      # doing what is called a belt & suspenders, so pip won't upgrade numpy further