name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.1
  - pip=23.3.1
  - pytest=8.0.2
  - scipy=1.12.0
  - numpy=1.23.5 
  - pip:
      - wandb==0.16.4
      - numpy==1.23.5      # doing what is called a belt & suspenders, so pip won't upgrade numpy further